# Generated by Django 3.2.13 on 2022-11-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
