# Generated by Django 4.1.4 on 2023-03-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
