# Generated by Django 4.1.4 on 2023-03-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_image_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
