# Generated by Django 4.1.4 on 2023-03-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default=1, upload_to='picture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='articles.article'),
        ),
    ]
