# Generated by Django 4.1.4 on 2023-03-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_picture_alter_postimage_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='picture',
        ),
    ]
