# Generated by Django 4.1.4 on 2023-04-04 06:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_delete_category_delete_tag_postimage_image_resize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image_resize',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1000, 1000], upload_to='image'),
        ),
    ]
